version: "3.8"

services:
  app:
    build: 
      context: .
    container_name: openai-streamlit-webapp
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    restart: unless-stopped 
    ports:
      - 8501:8501
    volumes:
      - .:/app
